### ISSUE TITLE
Secure your application

### ISSUE THREAD

**Issue by dibyasonu** [TheLethalCode/Artemis-arrow#9]
- Don't upload your api secrets...[bad move](https://github.com/TheLethalCode/Artemis-arrow/commit/e55e068ee816503eea2f01a03cac960e7fdd7267)

- It seems you have first uploaded the project then added gitignore. Don't do that. Git tracks everything so the files would be in commit history.

- **Git reset --soft** to the first commit and adding the proper gitignore and **force push** are your friends here to help the situation...

**Comment by TheLethalCode** [comment]
@dibyasonu I know, I have my api secrets lying around. That's because this was a private repository in the first place. Now those API credentials are useless, I have unregistered the app. For now, it is just for show. Thanks for pointing it out anyway. And anyway, even if we reset the local repo and force push. you can still find the file in git reflog. Git never loses track of files XD (So, you are never free XD). Closing Issue
